"""Cost segregation / depreciation engine constants."""

from __future__ import annotations

CALCULATION_SUPPORTED = "supported"
CALCULATION_UNSUPPORTED = "unsupported"
CALCULATION_MANUAL_REVIEW = "manual_review_required"
CALCULATION_INSUFFICIENT = "insufficient_information"

REASON_MID_QUARTER = "MID_QUARTER_NOT_IMPLEMENTED"
REASON_ADS = "ADS_NOT_IMPLEMENTED"
REASON_UNSUPPORTED_ASSET = "UNSUPPORTED_ASSET_CLASS"
REASON_LISTED_PROPERTY = "LISTED_PROPERTY_NOT_IMPLEMENTED"
REASON_SECTION_179 = "SECTION_179_NOT_IMPLEMENTED"

BONUS_REGIME_POST_2025 = "POST_2025_01_19_PERMANENT"
BONUS_REGIME_PRE_2025 = "PRE_2025_01_20_PHASEDOWN"

MODE_ESTIMATE = "estimate"
MODE_STUDY_BACKED = "study_backed"

ACTIVITY_RENTAL = "rental_real_estate"
